# Generated by Django 4.2.7 on 2024-01-28 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist_app', '0007_watchlist_avg_rating_watchlist_number_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
